server:
  port: 3000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: POS
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false


spring-docs:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
