spring:
  application:
    name: POS
  datasource:
    url: jdbc:sqlserver://127.0.0.1;databaseName=INTERN;trustServerCertificate=true
    username: intern
    password: intern
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect